version: '3'

services:

  rabbitmq:
    container_name: rabbit-3
    image: rabbitmq:3-management
    network_mode: host
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-plugin:/opt/rabbitmq/plugins
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
volumes:
  rabbit-data:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: $PWD/data
  rabbit-plugin:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: $PWD/plugins
